services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel-8-app:1.0
    container_name: qorus_app
    volumes:
      - .:/var/www/html
    ports:
      - "89:80" # Porta do Laravel
    depends_on:
      - db
    environment:
      - VIRTUAL_HOST=qorus.local
  db:
    image: mysql:8.0
    container_name: qorus_db
    restart: always
    environment:
      MYSQL_DATABASE: qorus_db
      MYSQL_USER: qorus_user
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3310:3306"
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata: